name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1


    - name: Log in to Azure Container Registry 
      run: |
        echo "${{ secrets.SP_PASSWORD }}" | docker login seliseacr.azurecr.io --username "${{ secrets.SP_APP_ID }}" --password-stdin


    - name: Build and Push Docker image
      run: |
        docker buildx build --platform linux/amd64 -t seliseacr.azurecr.io/selise-rest-api:v1 --push .

    - name: Deploy to AKS
      uses: azure/aks-set-context@v1
      with:
        resource-group: devops-assessment-rg
        cluster-name: selise-aks-cluster

    - name: Update deployment
      run: |
        kubectl set image deployment/selise-rest-api selise-rest-api=seliseacr.azurecr.io/selise-rest-api:v1 --record
