name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v1
        with:
          registry: seliseacr.azurecr.io
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      - name: Build and Push Docker image
        run: |
          docker buildx build --platform linux/amd64 -t seliseacr.azurecr.io/selise-rest-api:v1 --push .

      - name: Set up AKS context
        uses: azure/aks-set-context@v1
        with:
          resource-group: devops-assessment-rg
          cluster-name: selise-aks-cluster
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Update deployment
        run: |
          kubectl set image deployment/selise-rest-api selise-rest-api=seliseacr.azurecr.io/selise-rest-api:v1